version: "3.4"

services:
  get-tweets:
    build: "./get-tweets"
    volumes:
      - "tweets_data:/get_tweets/tweets/"
    env_file:
      - environment-variables.env

  train:
    build: "./train"
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - "tweets_data:/covfefe_flow/data/"
      - "models_data:/covfefe_flow/models/"
    env_file:
      - environment-variables.env

  tensorflow-serving:
    build: "./tensorflow-serving"

  api:
    build: "./api"
    depends_on:
      - tensorflow-serving
    env_file:
      - environment-variables.env

  webapp:
    build: ./webapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "certificates_data:/etc/ssl/:ro"
    depends_on:
      - api

  chatbot:
    build: ./chatbot
    depends_on:
      - api
    env_file:
      - environment-variables.env

  letsencrypt-certbot:
    image: "certbot/certbot:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "certificates_data:/etc/letsencrypt/"
    command: "certonly -n --standalone -m covfefe.flow@gmail.com --agree-tos --no-eff-email -d covfefe-flow.tk -d www.covfefe-flow.tk -d api.covfefe-flow.tk -d chatbot.covfefe-flow.tk"

volumes:
  tweets_data:
  models_data:
  certificates_data: