version: "3.4"

services:
  get-tweets:
    build: "./get-tweets"
    volumes:
      - "tweets_data:/get_tweets/tweets"
    env_file:
      - ./environment-variables.env

  train-rnn:
    build: "./train-rnn"
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - "tweets_data:/covfefe_flow/data"
      - "models_data:/covfefe_flow/models"
    env_file:
      - ./environment-variables.env

  tensorflow-serving:
    image: "epigramai/model-server:light-1.5"
    ports:
      - "9000:9000"
    volumes:
      - "models_data:/models/"
    command: ["--port=9000", "--model_name=covfefe-flow", "--model_base_path=/models/covfefe_flow"]

  serve-rnn:
    build: "./serve-rnn"
    ports:
      - "80:80"
    depends_on:
      - "tensorflow-serving"

volumes:
  tweets_data:
  models_data: