name: CI/CD

on: [push]

jobs:
  webapp:
    name: Webapp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: make webapp-install
    - run: make webapp-lint
    - run: make webapp-test-ci
    - run: make webapp-deploy-to-ghpages
      if: github.ref == 'refs/heads/primary'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: make api-install-dev
      - run: make api-lint
